//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Messages
    {
        public int messageId { get; set; }
        public int adminId { get; set; }
        public int simpleuserId { get; set; }
        public string subject { get; set; }
        public string bodyText { get; set; }
    }
}
