//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EN_Users : DbContext
    {
        public EN_Users()
            : base("name=EN_Users")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Profiles> tbl_Profiles { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
        public virtual DbSet<view_GetOnlySimpleusers> view_GetOnlySimpleusers { get; set; }
        public virtual DbSet<view_GetOnlyAdmins> view_GetOnlyAdmins { get; set; }
        public virtual DbSet<tbl_Messages> tbl_Messages { get; set; }
    }
}
